routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'HomeController@index')->name('inicio');

Auth::routes();

// Panel de Administración Routes...
Route::group(['namespace' => 'administrador', 'prefix' => 'admin', 'middleware' => ['auth', 'auth']], function () {
		Route::get('/home', 'DashboardController@index')->name('home');
		Route::resource('/coordinadores', 'CoordinadoresController');
		Route::resource('/docentes', 'DocentesController');
		Route::resource('/asignaturas', 'AsignaturasController');
		Route::resource('/categorias', 'CategoriaDocController');
		Route::resource('/documentos', 'DocumentosController');
		Route::resource('/eventos', 'EventosController');
		Route::resource('/cursos', 'CursosController');
		Route::resource('/subcurso', 'SubCursoController');
		// Admin Routes...
		/*Route::resource('/servicios', 'ServiciosController');*/
	});

app/Documento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Documento extends Model {
	public function categoria() {
		return $this->belongsTo('App\CategoriaDocument');
	}
}

app/Http/Controllers/administrador/DocumentosController.php
<?php

namespace App\Http\Controllers\administrador;

use App\Documento;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class DocumentosController extends Controller {
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		//
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request) {
		$validator = Validator::make($request->all(), [
				'title'       => 'required|string|max:255',
				'description' => 'required|string',
				'file'        => 'required|mimes:doc,pdf,docx,zip,xls',
			]);

		// Si la validación falla
		if ($validator->fails()) {
			return back()->with('error', 'Ups, no se ha podido agregar el item')->withInput()->withErrors($validator->errors());
		}
		$store              = new Documento;
		$nombreCategoria    = $request->input('nombre_categoria');
		$store->title       = $request->input('title');
		$store->description = $request->input('description');
		if ($request->hasFile('file')) {
			$fileas            = $request->file('file');
			$destinationPathas = 'documentos/'.$nombreCategoria.'/';
			$fileas->move($destinationPathas, $fileas->getClientOriginalName());
			$store->file = $destinationPathas.''.$fileas->getClientOriginalName();
		} else {
			$store->file = 'documentos/perfil.png';
		}
		$store->categoria_id = $request->input('categoria_id');
		$store->save();
		return back()->with('success', 'Item creado correctamente');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id) {
		$documento = Documento::find($id);
		return view('documentos.edit', compact('documento'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id) {
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id) {
		$validator = Validator::make($request->all(), [
				'title'       => 'required|string|max:255',
				'description' => 'required|string',
			]);

		// Si la validación falla
		if ($validator->fails()) {
			return back()->with('error', 'Ups, no se ha podido agregar el item')->withInput()->withErrors($validator->errors());
		}
		$store              = Documento::find($id);
		$nombreCategoria    = $request->input('nombre_categoria');
		$store->title       = $request->input('title');
		$store->description = $request->input('description');
		if ($request->hasFile('file')) {
			$fileas            = $request->file('file');
			$destinationPathas = 'documentos/'.$nombreCategoria.'/';
			$fileas->move($destinationPathas, $fileas->getClientOriginalName());
			$store->file = $destinationPathas.''.$fileas->getClientOriginalName();
		}
		$store->save();
		return back()->with('success', 'Item creado correctamente');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id) {
		$store = Documento::find($id);
		$store->delete();
		return back()->with('success', 'Item eliminado correctamente');
	}
}

resources/views/documentos/categorias.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid ">
		<nav class="navbar navbar-light  justify-content-between">
			<a class="navbar-brand text-bold-o">Categorias Documentos</a>
			<form class="form-inline">
				<a data-toggle="modal" data-target="#categorias" class="btn btn-success text-white btn-sm text-bold-o">
					<i class="fa fa-plus"></i> Nueva categoria
				</a>
				<input class="form-control ml-sm-2 form-control-sm" type="search" id="myInput" placeholder="Buscar..." aria-label="Search" onkeyup="myFunction()">
			</form>
		</nav>
    	<table class="table table-sm table-bordered dataTable text-regular-o" id="myTable">
    		<thead class="thead-dark small">
			    <tr>
			      <th scope="col">#</th>
			      <th scope="col">Titulo</th>
			      <th scope="col">Descripción</th>
			      {{-- <th scope="col">Correo personal</th>
			      <th scope="col">Dirección</th> --}}
			      {{-- <th scope="col">Eps</th> --}}
			      <th scope="col" colspan="2">Acciones</th>
			    </tr>
			</thead>
    		@foreach($categorias as $u)
    			<tr class="small text-center">
    				<th scope="row">{{$loop->iteration}}</th>
        			<td>
        				<span>{{ $u['title'] }}</span>
        			</td>
        			<td class="text-muted">
        				{!! \Illuminate\Support\Str::words($u['description'],50) !!}
        			</td>
        			<td>
        				<a href="{{ route('categorias.show', $u['id']) }}" class="btn btn-info btn-sm">
        					<i class="fa fa-pencil"></i> Editar
        				</a>
        			</td>
        			<td>
        				{!! Form::open(['route'=>['categorias.destroy',$u['id']],'method'=>'DELETE'])!!}
		               		<button onclick="return confirm('¿Está seguro de eliminar permanentemente a {{$u->title}}?');" class="btn btn-danger btn-sm text-left" type="submit"><i class="fa fa-remove" aria-hidden="true"></i> Eliminar</button>
		                {!! Form::close() !!}
        			</td>
        		</tr>
    		@endforeach
            @include('documentos.create')
    	</table>
    </div>
@endsection
@section('script')
@endsection

resources/views/documentos/create.blade.php
<!-- Modal -->
<div class="modal fade" id="documentos" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Agregar Documento</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {!! Form::open(['route'=>'documentos.store','method'=> 'POST','files'=>"true", 'enctype'=>"multipart/form-data"]) !!}
        {!! csrf_field() !!}
              <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                  <label for="title" class="">Nombre documento</label>
                  <input id="title" placeholder="..." type="text" class="form-control form-control-sm" name="title" value="{{ old('title') }}" required autofocus>
                  @if(isset($categoria))
                  <input type="hidden" value="{{ $categoria['title'] }}" name="nombre_categoria">
                  <input type="hidden" value="{{ $categoria['id'] }}" name="categoria_id">
                  @endif

                  @if ($errors->has('title'))
                      <span class="help-block">
                          <strong>{{ $errors->first('title') }}</strong>
                      </span>
                  @endif
              </div>
              <div class="form-group{{ $errors->has('file') ? ' has-error' : '' }}">
                  <label for="file" class="">Archivo</label>
                  <input id="file" type="file" class="form-control form-control-sm" name="file" value="{{ old('file') }}" required autofocus style="overflow: hidden;">

                  @if ($errors->has('file'))
                      <span class="help-block">
                          <strong>{{ $errors->first('file') }}</strong>
                      </span>
                  @endif
              </div>
              <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                  <label for="description" class="">Descripción del documento</label>
                  <textarea name="description" class="form-control form-control-sm description" id="description">{{ old('description') }}</textarea>

                  @if ($errors->has('description'))
                      <span class="help-block">
                          <strong>{{ $errors->first('description') }}</strong>
                      </span>
                  @endif
              </div>
            <div class="form-group text-center">
              {!! Form::submit('+ Registrar documento',['class'=>'d-block btn btn-primary btn-sm text-center']) !!}
            </div>
      {!! Form::close() !!}
      </div>
    </div>
  </div>
</div>



<!-- Modal -->
<div class="modal fade" id="categorias" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Agregar Categoria</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {!! Form::open(['route'=>'categorias.store','method'=> 'POST','files'=>"true", 'enctype'=>"multipart/form-data"]) !!}
        {!! csrf_field() !!}
              <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                  <label for="title" class="">Titulo categoria</label>
                  <input id="title" placeholder="..." type="text" class="form-control form-control-sm" name="title" value="{{ old('title') }}" required autofocus>

                  @if ($errors->has('title'))
                      <span class="help-block">
                          <strong>{{ $errors->first('title') }}</strong>
                      </span>
                  @endif
              </div>
              <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                  <label for="description" class="">Descripción de la categoria</label>
                  <textarea name="description" class="form-control form-control-sm description" id="description">{{ old('description') }}</textarea>

                  @if ($errors->has('description'))
                      <span class="help-block">
                          <strong>{{ $errors->first('description') }}</strong>
                      </span>
                  @endif
              </div>
            <div class="form-group text-center">
              {!! Form::submit('+ Registrar categoria',['class'=>'d-block btn btn-primary btn-sm text-center']) !!}
            </div>
      {!! Form::close() !!}
      </div>
    </div>
  </div>
</div>

resources/views/documentos/ctedit.blade.php
@extends('layouts.app')
@section('content')
    <link rel="stylesheet" href="{{ asset('css/bootstrap-datetimepicker.min.css') }}">
    <div class="container-fluid text-regular ">
		<nav class="navbar navbar-light  justify-content-between">
			<a class="navbar-brand text-bold"><i class="fa fa-plus-square"></i> Editar: {{ $categoria['title'] }}</a>
			<form class="form-inline">
				<a href="{{ route('categorias.index') }}" class="btn btn-danger btn-sm">
					<i class="fa fa-long-arrow-left"></i> Regresar
				</a>
			</form>
		</nav>
		<div class="x_panel bg-light">
	      	<div class="x_content row">
	      		@if(count($errors)!= 0)
		            <div class="alert alert-warning text-white" role="alert">
						@foreach ($errors->all() as $error)
							<div>{{ $error }}</div>
						@endforeach
		            </div>
		        @endif
		        @include('includes.alert')
		       	<!-- Formulario ADD Proyecto -->
	          	<div class="ml-4 col-md-12 col-xs-12">
	          		{!! Form::open(['route'=>['categorias.update', $categoria['id']],'method'=> 'PUT','files'=>"true", 'enctype'=>"multipart/form-data"]) !!}
		          		{!! csrf_field() !!}
                        <div class="row">
                            <div class="col">
                                <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                  <label for="title" class="">Titulo categoria</label>
                                  <input id="title" placeholder="..." type="text" class="form-control form-control-sm" name="title" value="{{ old('title') }}{{ $categoria['title'] }}" required autofocus>

                                  @if ($errors->has('title'))
                                      <span class="help-block">
                                          <strong>{{ $errors->first('title') }}</strong>
                                      </span>
                                  @endif
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                  <label for="description" class="">Descripción:</label>
                                  <textarea name="description" class="form-control form-control-sm description" id="description">{{ old('description') }}{{ $categoria['description'] }}</textarea>

                                  @if ($errors->has('description'))
                                      <span class="help-block">
                                          <strong>{{ $errors->first('description') }}</strong>
                                      </span>
                                  @endif
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group text-center">
                                {!! Form::submit('+ Actualizar categoria',['class'=>'d-block btn btn-success btn-sm text-center']) !!}
                                </div>
                            </div>
                        </div>
		          	{!! Form::close() !!}
	          	</div>
	      	</div>
		</div>
    </div>
    <div class="container-fluid ">
        <nav class="navbar navbar-light  justify-content-between">
            <a class="navbar-brand text-bold-o">Documentos</a>
            <form class="form-inline">
                <a data-toggle="modal" data-target="#documentos" class="btn btn-warning text-white btn-sm text-bold-o">
                    <i class="fa fa-plus"></i> Nuevo Documento
                </a>
                <input class="form-control ml-sm-2 form-control-sm" type="search" id="myInput" placeholder="Buscar..." aria-label="Search" onkeyup="myFunction()">
            </form>
        </nav>
        <table class="table table-sm table-bordered dataTable text-regular-o" id="myTable">
            <thead class="thead-dark small">
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Titulo</th>
                  <th scope="col">File</th>
                  <th scope="col">Descripción</th>
                  {{-- <th scope="col">Correo personal</th>
                  <th scope="col">Dirección</th> --}}
                  {{-- <th scope="col">Eps</th> --}}
                  <th scope="col" colspan="2">Acciones</th>
                </tr>
            </thead>
            @foreach($categoria->documentos as $u)
                <tr class="small text-center">
                    <th scope="row">{{$loop->iteration}}</th>
                    <td>
                        <span>{{ $u['title'] }}</span>
                    </td>
                    <td>
                        <a href="{{ asset($u['file']) }}" target="_blank">Ver documento</a>
                    </td>
                    <td class="text-muted">
                        {!! \Illuminate\Support\Str::words($u['description'],50) !!}
                    </td>
                    <td>
                        <a href="{{ route('documentos.show', $u['id']) }}?url={{ url()->previous() }}&nombre_categoria={{ $categoria['title'] }}" class="btn btn-info btn-sm">
                            <i class="fa fa-pencil"></i> Editar
                        </a>
                    </td>
                    <td>
                        {!! Form::open(['route'=>['documentos.destroy',$u['id']],'method'=>'DELETE'])!!}
                            <button onclick="return confirm('¿Está seguro de eliminar permanentemente a {{$u->title}}?');" class="btn btn-danger btn-sm text-left" type="submit"><i class="fa fa-remove" aria-hidden="true"></i> Eliminar</button>
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            @include('documentos.create')
        </table>
    </div>
@endsection
@section('script')
@endsection

resources/views/documentos/edit.blade.php
@extends('layouts.app')
@section('content')
    <link rel="stylesheet" href="{{ asset('css/bootstrap-datetimepicker.min.css') }}">
    <div class="container-fluid text-regular ">
    <nav class="navbar navbar-light  justify-content-between">
      <a class="navbar-brand text-bold"><i class="fa fa-plus-square"></i> Editar: {{ $documento['title'] }}</a>
      <form class="form-inline">
        <a href="{{ $_GET['url'] }}" class="btn btn-danger btn-sm">
          <i class="fa fa-long-arrow-left"></i> Regresar
        </a>
      </form>
    </nav>
    <div class="x_panel bg-light">
          <div class="x_content row">
            @if(count($errors)!= 0)
                <div class="alert alert-warning text-white" role="alert">
            @foreach ($errors->all() as $error)
              <div>{{ $error }}</div>
            @endforeach
                </div>
            @endif
            @include('includes.alert')
            <!-- Formulario ADD Proyecto -->
              <div class="ml-4 col-md-8 col-xs-12">
                {!! Form::open(['route'=>['documentos.update', $documento['id']],'method'=> 'PUT','files'=>"true", 'enctype'=>"multipart/form-data"]) !!}
                  {!! csrf_field() !!}
                  <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                    <label for="title" class="">Titulo documento</label>
                    <input id="title" placeholder="..." type="text" class="form-control form-control-sm" name="title" value="{{ $documento['title'] }}" required autofocus>
                    @if(isset($_GET['nombre_categoria']))
                    <input type="hidden" value="{{ $_GET['nombre_categoria'] }}" name="nombre_categoria">
                    @endif

                    @if ($errors->has('title'))
                        <span class="help-block">
                            <strong>{{ $errors->first('title') }}</strong>
                        </span>
                    @endif
                  </div>
                  <div class="form-group{{ $errors->has('file') ? ' has-error' : '' }}">
                    <label for="file" class="">Archivo</label>
                    <input id="file" type="file" class="form-control form-control-sm" name="file" value="{{ $documento['file'] }}{{ old('file') }}"  autofocus style="overflow: hidden;">

                    @if ($errors->has('file'))
                        <span class="help-block">
                            <strong>{{ $errors->first('file') }}</strong>
                        </span>
                    @endif
                </div>
                  <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                    <label for="description" class="">Descripción:</label>
                    <textarea name="description" class="form-control form-control-sm description" id="description">{{ $documento['description'] }}</textarea>

                    @if ($errors->has('description'))
                        <span class="help-block">
                            <strong>{{ $errors->first('description') }}</strong>
                        </span>
                    @endif
                  </div>
                  <div class="form-group text-center">
                  {!! Form::submit('+ Actualizar documento',['class'=>'d-block btn btn-success btn-sm text-center']) !!}
                  </div>
                        </div>
                {!! Form::close() !!}
              </div>
          </div>
    </div>
@endsection
@section('script')
@endsection