routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'HomeController@index')->name('inicio');

Auth::routes();

// Panel de Administración Routes...
Route::group(['namespace' => 'administrador', 'prefix' => 'admin', 'middleware' => ['auth', 'auth']], function () {
		Route::get('/home', 'DashboardController@index')->name('home');
		Route::resource('/coordinadores', 'CoordinadoresController');
		Route::resource('/docentes', 'DocentesController');
		Route::resource('/asignaturas', 'AsignaturasController');
		Route::resource('/categorias', 'CategoriaDocController');
		Route::resource('/documentos', 'DocumentosController');
		Route::resource('/eventos', 'EventosController');
		Route::resource('/cursos', 'CursosController');
		Route::resource('/subcurso', 'SubCursoController');
		// Admin Routes...
		/*Route::resource('/servicios', 'ServiciosController');*/
	});

app/Http/Controllers/administrador/EventosController.php
<?php

namespace App\Http\Controllers\administrador;

use App\admin\Evento;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class EventosController extends Controller {
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		$eventos = Evento::all();
		return view('eventos.index', compact('eventos'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('eventos.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request) {
		$validator = Validator::make($request->all(), [
				'title'       => 'required|string|max:255',
				'description' => 'required|string',
				'start_date'  => 'required|string',
				'end_date'    => 'required|string',
			]);

		// Si la validación falla
		if ($validator->fails()) {
			return back()->with('error', 'Ups, no se ha podido agregar el item')->withInput()->withErrors($validator->errors());
		}
		$store              = new Evento;
		$store->title       = $request->input('title');
		$store->description = $request->input('description');
		if ($request->hasFile('icon')) {
			$fileas            = $request->file('icon');
			$destinationPathas = 'images/eventos/';
			$fileas->move($destinationPathas, $fileas->getClientOriginalName());
			$store->icon = $destinationPathas.''.$fileas->getClientOriginalName();
		} else {
			$store->icon = 'images/perfil.png';
		}
		if ($request->hasFile('image')) {
			$fileaf            = $request->file('image');
			$destinationPathaf = 'images/eventos/';
			$fileaf->move($destinationPathaf, $fileaf->getClientOriginalName());
			$store->file = $destinationPathaf.''.$fileaf->getClientOriginalName();
		} else {
			$store->file = 'images/perfil.png';
		}
		$store->start_date = $request->input('start_date');
		$store->end_date   = $request->input('end_date');
		$store->save();
		return back()->with('success', 'Item creado correctamente');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id) {
		$evento = Evento::find($id);
		return view('eventos.edit', compact('evento'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id) {
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id) {
		$store              = Evento::find($id);
		$store->title       = $request->input('title');
		$store->description = $request->input('description');
		if ($request->hasFile('icon')) {
			$fileas            = $request->file('icon');
			$destinationPathas = 'images/eventos/';
			$fileas->move($destinationPathas, $fileas->getClientOriginalName());
			$store->icon = $destinationPathas.''.$fileas->getClientOriginalName();
		}
		if ($request->hasFile('image')) {
			$fileaf            = $request->file('image');
			$destinationPathaf = 'images/eventos/';
			$fileaf->move($destinationPathaf, $fileaf->getClientOriginalName());
			$store->file = $destinationPathaf.''.$fileaf->getClientOriginalName();
		}
		$store->start_date = $request->input('start_date');
		$store->end_date   = $request->input('end_date');
		$store->update();
		return back()->with('success', 'Item actualizado correctamente');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id) {
		$evento = Evento::find($id);
		$evento->delete();
		return back();
	}
}

resources/views/eventos/create.blade.php
@extends('layouts.app')
@section('content')
    <link rel="stylesheet" href="{{ asset('css/bootstrap-datetimepicker.min.css') }}">
    <div class="container-fluid text-regular ">
		<nav class="navbar navbar-light  justify-content-between">
			<a class="navbar-brand text-bold"><i class="fa fa-plus-square"></i> Crear evento</a>
			<form class="form-inline">
				<a href="{{ route('eventos.index') }}" class="btn btn-danger btn-sm">
					<i class="fa fa-long-arrow-left"></i> Regresar
				</a>
			</form>
		</nav>
		<div class="x_panel bg-light">
	      	<div class="x_content row">
	      		@if(count($errors)!= 0)
		            <div class="alert alert-warning text-white" role="alert">
						@foreach ($errors->all() as $error)
							<div>{{ $error }}</div>
						@endforeach
		            </div>
		        @endif
		        @include('includes.alert')
		       	<!-- Formulario ADD Proyecto -->
	          	<div class="ml-4 col-md-8 col-xs-12">
	          		{!! Form::open(['route'=>'eventos.store','method'=> 'POST','files'=>"true", 'enctype'=>"multipart/form-data"]) !!}
		          		{!! csrf_field() !!}
                        <div class="row">
                            <div class="col">
                                <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                    <label for="title" class="">Titulo del evento</label>
                                    <input id="title" placeholder="juanito perez" type="text" class="form-control form-control-sm" name="title" value="{{ old('title') }}" required autofocus>

                                    @if ($errors->has('title'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('title') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group{{ $errors->has('icon') ? ' has-error' : '' }}">
                                    <label for="icon" class="">Icono thubmnail </label>
                                    <input id="icon" type="file" class="form-control form-control-sm" name="icon" value="{{ old('icon') }}" required autofocus style="overflow: hidden;">

                                    @if ($errors->has('icon'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('icon') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
                                    <label for="image" class="">Imagen (800x800)</label>
                                    <input id="image" type="file" class="form-control form-control-sm" name="image" value="{{ old('image') }}" required autofocus style="overflow: hidden;">

                                    @if ($errors->has('image'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('image') }}</strong>
                                        </span>
                                    @endif
                                </div>

                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="">Descripción</label>
                            <textarea name="description" class="form-control form-control-sm description" id="description">{{ old('description') }}</textarea>

                            @if ($errors->has('description'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('description') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="form-group{{ $errors->has('start_date') ? ' has-error' : '' }} ">
                                    <label for="start_date" class="">Fecha de inicio</label>
                                    <input id="datetimepicker1" type="text" class=" form-control form-control-sm" name="start_date" value="{{ old('start_date') }}" required >
                                    @if ($errors->has('start_date'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('start_date') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col">
        						<div class="form-group{{ $errors->has('end_date') ? ' has-error' : '' }}">
                                    <label for="end_date" class="">Fecha final</label>
                                    <input id="datetimepicker2" type="text" class="date form-control form-control-sm" name="end_date" value="{{ old('end_date') }}" required autofocus>

                                    @if ($errors->has('end_date'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('end_date') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                        </div>
                    	<div class="form-group text-center">
                    		{!! Form::submit('+ Registrar evento',['class'=>'d-block btn btn-primary btn-sm text-center']) !!}
                    	</div>
		          	{!! Form::close() !!}
	          	</div>
	      	</div>
		</div>
    </div>
@endsection
@section('script')
    @include('includes.tinymce')
    <script type="text/javascript" src="{{ asset('js/moment.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/bootstrap-datetimepicker.min.js') }}"></script>
    <script src="{{ asset('js/es-us.js') }}"></script>

    <script>
        $(function () {
            $('#datetimepicker1, #datetimepicker2').datetimepicker({
                format: 'YYYY-MM-DD hh:mm:ss',

                // daysOfWeekDisabled: [0, 6]
            });
        });
    </script>
@endsection

resources/views/eventos/edit.blade.php
@extends('layouts.app')
@section('content')
    <link rel="stylesheet" href="{{ asset('css/bootstrap-datetimepicker.min.css') }}">
    <div class="container-fluid text-regular ">
		<nav class="navbar navbar-light  justify-content-between">
			<a class="navbar-brand text-bold"><i class="fa fa-plus-square"></i> Editar: {{ $evento['title'] }}</a>
			<form class="form-inline">
				<a href="{{ route('eventos.index') }}" class="btn btn-danger btn-sm">
					<i class="fa fa-long-arrow-left"></i> Regresar
				</a>
			</form>
		</nav>
		<div class="x_panel bg-light">
	      	<div class="x_content row">
	      		@if(count($errors)!= 0)
		            <div class="alert alert-warning text-white" role="alert">
						@foreach ($errors->all() as $error)
							<div>{{ $error }}</div>
						@endforeach
		            </div>
		        @endif
		        @include('includes.alert')
		       	<!-- Formulario ADD Proyecto -->
	          	<div class="ml-4 col-md-8 col-xs-12">
	          		{!! Form::open(['route'=>['eventos.update', $evento['id']],'method'=> 'PUT','files'=>"true", 'enctype'=>"multipart/form-data"]) !!}
		          		{!! csrf_field() !!}
                        <div class="row">
                            <div class="col">
                                <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                    <label for="title" class="">Titulo del evento</label>
                                    <input id="title" placeholder="juanito perez" type="text" class="form-control form-control-sm" name="title" value="{{ $evento['title'] }}{{ old('title') }}" required autofocus>

                                    @if ($errors->has('title'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('title') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group{{ $errors->has('icon') ? ' has-error' : '' }}">
                                    <label for="icon" class="">Icono thubmnail </label>
                                    <input id="icon" type="file" class="form-control form-control-sm" name="icon" value="{{ $evento['icon'] }}{{ old('icon') }}"  autofocus style="overflow: hidden;">

                                    @if ($errors->has('icon'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('icon') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
                                    <label for="image" class="">Imagen (800x800)</label>
                                    <input id="image" type="file" class="form-control form-control-sm" name="image" value="{{ $evento['file'] }}{{ old('image') }}"  autofocus style="overflow: hidden;">

                                    @if ($errors->has('image'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('image') }}</strong>
                                        </span>
                                    @endif
                                </div>

                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="">Descripción</label>
                            <textarea name="description" class="form-control form-control-sm description" id="description">{{ $evento['description'] }}</textarea>

                            @if ($errors->has('description'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('description') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="form-group{{ $errors->has('start_date') ? ' has-error' : '' }} ">
                                    <label for="start_date" class="">Fecha de inicio</label>
                                    <input id="datetimepicker1" type="text" class=" form-control form-control-sm" name="start_date" value="{{ $evento['start_date'] }}{{ old('start_date') }}" required >
                                    @if ($errors->has('start_date'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('start_date') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col">
        						<div class="form-group{{ $errors->has('end_date') ? ' has-error' : '' }}">
                                    <label for="end_date" class="">Fecha final</label>
                                    <input id="datetimepicker2" type="text" class="date form-control form-control-sm" name="end_date" value="{{ $evento['end_date'] }}{{ old('end_date') }}" required autofocus>

                                    @if ($errors->has('end_date'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('end_date') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                        </div>
                    	<div class="form-group text-center">
                    		{!! Form::submit('+ Actualizar',['class'=>'d-block btn btn-success btn-sm text-center']) !!}
                    	</div>
		          	{!! Form::close() !!}
	          	</div>
	      	</div>
		</div>
    </div>
@endsection
@section('script')
    @include('includes.tinymce')
    <script type="text/javascript" src="{{ asset('js/moment.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/bootstrap-datetimepicker.min.js') }}"></script>
    <script src="{{ asset('js/es-us.js') }}"></script>

    <script>
        $(function () {
            $('#datetimepicker1, #datetimepicker2').datetimepicker({
                format: 'YYYY-MM-DD hh:mm:ss',

                // daysOfWeekDisabled: [0, 6]
            });
        });
    </script>
@endsection

resources/views/eventos/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid ">
		<nav class="navbar navbar-light  justify-content-between">
			<a class="navbar-brand text-bold-o">Eventos Educativos</a>
			<form class="form-inline">
				<a href="{{ route('eventos.create') }}" class="btn btn-success btn-sm text-bold-o">
					<i class="fa fa-plus"></i> Nuevo evento
				</a>
				<input class="form-control ml-sm-2 form-control-sm" type="search" id="myInput" placeholder="Buscar..." aria-label="Search" onkeyup="myFunction()">
			</form>
		</nav>
    	<table class="table table-sm table-bordered dataTable text-regular-o" id="myTable">
    		<thead class="thead-dark small">
			    <tr>
			      <th scope="col">#</th>
			      <th scope="col">Titulo</th>
			      <th scope="col">Icono</th>
			      <th scope="col">Imagen</th>
			      <th scope="col">Descripción</th>
			      <th scope="col">Fecha inicio</th>
			      <th scope="col">Fecha final</th>
			      {{-- <th scope="col">Correo personal</th>
			      <th scope="col">Dirección</th> --}}
			      {{-- <th scope="col">Eps</th> --}}
			      <th scope="col" colspan="2">Acciones</th>
			    </tr>
			</thead>
    		@foreach($eventos as $u)
    			<tr class="small text-center">
    				<th scope="row">{{$loop->iteration}}</th>
        			<td>
        				<span>{{ $u['title'] }}</span>
        			</td>
        			<td>
        				<img src="{{ asset($u['icon']) }}" alt="" class=" img-fluid d-block" style="height: 20px;">
        			</td>
    				<td>
        				<img src="{{ asset($u['file']) }}" alt="" class=" img-fluid d-block" style="height: 30px;">
        			</td>
        			<td class="text-muted">
        				{!! \Illuminate\Support\Str::words($u['description'],50) !!}
        			</td>
        			<td>
        				<span>{{ $u['start_date'] }}</span>
        			</td>
        			<td>
        				<span>{{ $u['end_date'] }}</span>
        			</td>
        			<td>
        				<a href="{{ route('eventos.show', $u['id']) }}" class="btn btn-info btn-sm">
        					<i class="fa fa-pencil"></i> Editar
        				</a>
        			</td>
        			<td>
        				{!! Form::open(['route'=>['eventos.destroy',$u['id']],'method'=>'DELETE'])!!}
		               		<button onclick="return confirm('¿Está seguro de eliminar permanentemente a {{$u->title}}?');" class="btn btn-danger btn-sm text-left" type="submit"><i class="fa fa-remove" aria-hidden="true"></i> Eliminar</button>
		                {!! Form::close() !!}
        			</td>
        		</tr>
    		@endforeach
    	</table>
    </div>
@endsection
@section('script')
@endsection