routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'HomeController@index')->name('inicio');

Auth::routes();

// Panel de Administración Routes...
Route::group(['namespace' => 'administrador', 'prefix' => 'admin', 'middleware' => ['auth', 'auth']], function () {
		Route::get('/home', 'DashboardController@index')->name('home');
		Route::resource('/coordinadores', 'CoordinadoresController');
		Route::resource('/docentes', 'DocentesController');
		Route::resource('/asignaturas', 'AsignaturasController');
		Route::resource('/categorias', 'CategoriaDocController');
		Route::resource('/documentos', 'DocumentosController');
		Route::resource('/eventos', 'EventosController');
		Route::resource('/cursos', 'CursosController');
		Route::resource('/subcurso', 'SubCursoController');
		// Admin Routes...
		/*Route::resource('/servicios', 'ServiciosController');*/
	});

app/Http/Controllers/administrador/CursosController.php
<?php

namespace App\Http\Controllers\administrador;

use App\admin\Curso;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CursosController extends Controller {
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		$users = User::whereHas('roles', function ($q) {
				$q->where('name', 'docente');
			})->get();
		$cursos = Curso::all();
		return view('cursos.categorias', compact('cursos', 'users'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request) {
		$validator = Validator::make($request->all(), [
				'title'       => 'required|string|max:255',
				'description' => 'required|string',
				'user_id'     => 'required',
			]);

		// Si la validación falla
		if ($validator->fails()) {
			return back()->with('error', 'Ups, no se ha podido agregar el item')->withInput()->withErrors($validator->errors());
		}
		$store              = new Curso;
		$store->title       = $request->input('title');
		$store->descripcion = $request->input('description');
		$store->user_id     = $request->input('user_id');
		$store->save();
		return back()->with('success', 'Item creado correctamente');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id) {
		$users = User::whereHas('roles', function ($q) {
				$q->where('name', 'docente');
			})->get();
		$curso = Curso::find($id);
		return view('cursos.ctedit', compact('curso', 'users'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id) {
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id) {
		$validator = Validator::make($request->all(), [
				'title'       => 'required|string|max:255',
				'description' => 'required|string',
			]);

		// Si la validación falla
		if ($validator->fails()) {
			return back()->with('error', 'Ups, no se ha podido agregar el item')->withInput()->withErrors($validator->errors());
		}
		$store              = Curso::find($id);
		$store->title       = $request->input('title');
		$store->descripcion = $request->input('description');
		$store->user_id     = $request->input('user_id');
		$store->update();
		return back()->with('success', 'Item actualizado correctamente');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id) {
		$store = Curso::find($id);
		$store->delete();
		return back()->with('success', 'Item eliminado correctamente');
	}
}

resources/views/cursos/categorias.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid ">
		<nav class="navbar navbar-light  justify-content-between">
			<a class="navbar-brand text-bold-o">Cursos</a>
			<form class="form-inline">
				<a data-toggle="modal" data-target="#cursos" class="btn btn-success text-white btn-sm text-bold-o">
					<i class="fa fa-plus"></i> Nuevo curso
				</a>
				<input class="form-control ml-sm-2 form-control-sm" type="search" id="myInput" placeholder="Buscar..." aria-label="Search" onkeyup="myFunction()">
			</form>
		</nav>
    	<table class="table table-sm table-bordered dataTable text-regular-o" id="myTable">
    		<thead class="thead-dark small">
			    <tr>
			      <th scope="col">#</th>
			      <th scope="col">Titulo</th>
                  <th scope="col">Descripción</th>
			      <th scope="col">Docente Titular</th>
			      {{-- <th scope="col">Correo personal</th>
			      <th scope="col">Dirección</th> --}}
			      {{-- <th scope="col">Eps</th> --}}
			      <th scope="col" colspan="2">Acciones</th>
			    </tr>
			</thead>
    		@foreach($cursos as $u)
    			<tr class="small text-center">
    				<th scope="row">{{$loop->iteration}}</th>
        			<td>
        				<span>{{ $u['title'] }}</span>
        			</td>
                    <td class="text-muted">
                        {!! \Illuminate\Support\Str::words($u['descripcion'],50) !!}
                    </td>
        			<td class="text-muted">
                        @foreach($users as $us)
                            @if($us['id'] == $u['user_id'])
                                {{ $us['name'] }}
                            @endif
                        @endforeach
        			</td>
        			<td>
        				<a href="{{ route('cursos.show', $u['id']) }}" class="btn btn-info btn-sm">
        					<i class="fa fa-pencil"></i> Editar
        				</a>
        			</td>
        			<td>
        				{!! Form::open(['route'=>['cursos.destroy',$u['id']],'method'=>'DELETE'])!!}
		               		<button onclick="return confirm('¿Está seguro de eliminar permanentemente a {{$u->title}}?');" class="btn btn-danger btn-sm text-left" type="submit"><i class="fa fa-remove" aria-hidden="true"></i> Eliminar</button>
		                {!! Form::close() !!}
        			</td>
        		</tr>
    		@endforeach
            @include('cursos.create')
    	</table>
    </div>
@endsection
@section('script')
@endsection

resources/views/cursos/create.blade.php
<!-- Modal -->
<div class="modal fade" id="sub" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Agregar Sub curso</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {!! Form::open(['route'=>'subcurso.store','method'=> 'POST','files'=>"true", 'enctype'=>"multipart/form-data"]) !!}
        {!! csrf_field() !!}
              <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                  <label for="title" class="">Nombre curso</label>
                  <input id="title" placeholder="..." type="text" class="form-control form-control-sm" name="title" value="{{ old('title') }}" required autofocus>
                  @if(isset($curso))
                  <input type="hidden" value="{{ $curso['id'] }}" name="curso_id">
                  @endif

                  @if ($errors->has('title'))
                      <span class="help-block">
                          <strong>{{ $errors->first('title') }}</strong>
                      </span>
                  @endif
              </div>
              <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                  <label for="description" class="">Descripción del subcurso</label>
                  <textarea name="description" class="form-control form-control-sm description" id="description">{{ old('description') }}</textarea>

                  @if ($errors->has('description'))
                      <span class="help-block">
                          <strong>{{ $errors->first('description') }}</strong>
                      </span>
                  @endif
              </div>
            <div class="form-group text-center">
              {!! Form::submit('+ Registrar subcurso',['class'=>'d-block btn btn-primary btn-sm text-center']) !!}
            </div>
      {!! Form::close() !!}
      </div>
    </div>
  </div>
</div>



<!-- Modal -->
<div class="modal fade" id="cursos" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Agregar Cursos</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {!! Form::open(['route'=>'cursos.store','method'=> 'POST','files'=>"true", 'enctype'=>"multipart/form-data"]) !!}
        {!! csrf_field() !!}
              <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                  <label for="title" class="">Titulo curso</label>
                  <input id="title" placeholder="..." type="text" class="form-control form-control-sm" name="title" value="{{ old('title') }}" required autofocus>

                  @if ($errors->has('title'))
                      <span class="help-block">
                          <strong>{{ $errors->first('title') }}</strong>
                      </span>
                  @endif
              </div>
              <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                  <label for="description" class="">Descripción del curso</label>
                  <textarea name="description" class="form-control form-control-sm description" id="description">{{ old('description') }}</textarea>

                  @if ($errors->has('description'))
                      <span class="help-block">
                          <strong>{{ $errors->first('description') }}</strong>
                      </span>
                  @endif
              </div>
              <div class="form-group{{ $errors->has('user_id') ? ' has-error' : '' }}">
                  <label for="user_id" class="">Docente titular</label>
                  <select name="user_id" class="form-control form-control-sm" id="">
                    <option value=""> seleccionar</option>
                    @foreach($users as $us)
                      <option value="{{ $us['id'] }}" >{{ $us['name'] }}</option>
                    @endforeach
                  </select>

                  @if ($errors->has('user_id'))
                      <span class="help-block">
                          <strong>{{ $errors->first('user_id') }}</strong>
                      </span>
                  @endif
              </div>
            <div class="form-group text-center">
              {!! Form::submit('+ Registrar cursos',['class'=>'d-block btn btn-primary btn-sm text-center']) !!}
            </div>
      {!! Form::close() !!}
      </div>
    </div>
  </div>
</div>

resources/views/cursos/ctedit.blade.php
@extends('layouts.app')
@section('content')
    <link rel="stylesheet" href="{{ asset('css/bootstrap-datetimepicker.min.css') }}">
    <div class="container-fluid text-regular ">
		<nav class="navbar navbar-light  justify-content-between">
			<a class="navbar-brand text-bold"><i class="fa fa-plus-square"></i> Editar: {{ $curso['title'] }}</a>
			<form class="form-inline">
				<a href="{{ route('cursos.index') }}" class="btn btn-danger btn-sm">
					<i class="fa fa-long-arrow-left"></i> Regresar
				</a>
			</form>
		</nav>
		<div class="x_panel bg-light">
	      	<div class="x_content row">
	      		@if(count($errors)!= 0)
		            <div class="alert alert-warning text-white" role="alert">
						@foreach ($errors->all() as $error)
							<div>{{ $error }}</div>
						@endforeach
		            </div>
		        @endif
		        @include('includes.alert')
		       	<!-- Formulario ADD Proyecto -->
	          	<div class="ml-4 col-md-12 col-xs-12">
	          		{!! Form::open(['route'=>['cursos.update', $curso['id']],'method'=> 'PUT','files'=>"true", 'enctype'=>"multipart/form-data"]) !!}
		          		{!! csrf_field() !!}
                        <div class="row">
                            <div class="col">
                                <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                  <label for="title" class="">Titulo curso</label>
                                  <input id="title" placeholder="..." type="text" class="form-control form-control-sm" name="title" value="{{ $curso['title'] }}" required autofocus>

                                  @if ($errors->has('title'))
                                      <span class="help-block">
                                          <strong>{{ $errors->first('title') }}</strong>
                                      </span>
                                  @endif
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                  <label for="description" class="">Descripción:</label>
                                  <textarea name="description" class="form-control form-control-sm description" id="description">{{ $curso['descripcion'] }}</textarea>

                                  @if ($errors->has('description'))
                                      <span class="help-block">
                                          <strong>{{ $errors->first('description') }}</strong>
                                      </span>
                                  @endif
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group{{ $errors->has('user_id') ? ' has-error' : '' }}">
                                  <label for="user_id" class="">Docente titular</label>
                                  <select name="user_id" class="form-control form-control-sm" id="">
                                    @foreach($users as $us)
                                      <option value="{{ $us['id'] }}" @if($us['id'] == $curso['user_id']) selected="selected" @endif>{{ $us['name'] }}</option>
                                    @endforeach
                                  </select>

                                  @if ($errors->has('user_id'))
                                      <span class="help-block">
                                          <strong>{{ $errors->first('user_id') }}</strong>
                                      </span>
                                  @endif
                              </div>
                            </div>
                            <div class="col">
                                <div class="form-group text-center">
                                {!! Form::submit('+ Actualizar curso',['class'=>'d-block btn btn-success btn-sm text-center']) !!}
                                </div>
                            </div>
                        </div>
		          	{!! Form::close() !!}
	          	</div>
	      	</div>
		</div>
    </div>
    <div class="container-fluid ">
        <nav class="navbar navbar-light  justify-content-between">
            <a class="navbar-brand text-bold-o">Sub categoria de cursos</a>
            <form class="form-inline">
                <a data-toggle="modal" data-target="#sub" class="btn btn-warning text-white btn-sm text-bold-o">
                    <i class="fa fa-plus"></i> Nuevo sub curso
                </a>
                <input class="form-control ml-sm-2 form-control-sm" type="search" id="myInput" placeholder="Buscar..." aria-label="Search" onkeyup="myFunction()">
            </form>
        </nav>
        <table class="table table-sm table-bordered dataTable text-regular-o" id="myTable">
            <thead class="thead-dark small">
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Titulo</th>
                  <th scope="col">Descripción</th>
                  {{-- <th scope="col">Correo personal</th>
                  <th scope="col">Dirección</th> --}}
                  {{-- <th scope="col">Eps</th> --}}
                  <th scope="col" colspan="2">Acciones</th>
                </tr>
            </thead>
            @foreach($curso->sub_cursos as $u)
                <tr class="small text-center">
                    <th scope="row">{{$loop->iteration}}</th>
                    <td>
                        <span>{{ $u['title'] }}</span>
                    </td>
                    <td class="text-muted">
                        {!! \Illuminate\Support\Str::words($u['descripcion'],50) !!}
                    </td>
                    <td>
                        <a href="{{ route('subcurso.show', $u['id']) }}?url={{ url()->previous() }}" class="btn btn-info btn-sm">
                            <i class="fa fa-pencil"></i> Editar
                        </a>
                    </td>
                    <td>
                        {!! Form::open(['route'=>['subcurso.destroy',$u['id']],'method'=>'DELETE'])!!}
                            <button onclick="return confirm('¿Está seguro de eliminar permanentemente a {{$u->title}}?');" class="btn btn-danger btn-sm text-left" type="submit"><i class="fa fa-remove" aria-hidden="true"></i> Eliminar</button>
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            @include('cursos.create')
        </table>
    </div>
@endsection
@section('script')
@endsection

resources/views/cursos/edit.blade.php
@extends('layouts.app')
@section('content')
    <link rel="stylesheet" href="{{ asset('css/bootstrap-datetimepicker.min.css') }}">
    <div class="container-fluid text-regular ">
    <nav class="navbar navbar-light  justify-content-between">
      <a class="navbar-brand text-bold"><i class="fa fa-plus-square"></i> Editar: {{ $subcurso['title'] }}</a>
      <form class="form-inline">
        <a href="{{ $_GET['url'] }}" class="btn btn-danger btn-sm">
          <i class="fa fa-long-arrow-left"></i> Regresar
        </a>
      </form>
    </nav>
    <div class="x_panel bg-light">
          <div class="x_content row">
            @if(count($errors)!= 0)
                <div class="alert alert-warning text-white" role="alert">
            @foreach ($errors->all() as $error)
              <div>{{ $error }}</div>
            @endforeach
                </div>
            @endif
            @include('includes.alert')
            <!-- Formulario ADD Proyecto -->
              <div class="ml-4 col-md-8 col-xs-12">
                {!! Form::open(['route'=>['subcurso.update', $subcurso['id']],'method'=> 'PUT','files'=>"true", 'enctype'=>"multipart/form-data"]) !!}
                  {!! csrf_field() !!}
                  <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                    <label for="title" class="">Titulo subcurso</label>
                    <input id="title" placeholder="..." type="text" class="form-control form-control-sm" name="title" value="{{ $subcurso['title'] }}" required autofocus>
                    @if(isset($_GET['nombre_categoria']))
                    <input type="hidden" value="{{ $_GET['nombre_categoria'] }}" name="nombre_categoria">
                    @endif

                    @if ($errors->has('title'))
                        <span class="help-block">
                            <strong>{{ $errors->first('title') }}</strong>
                        </span>
                    @endif
                  </div>
                  <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                    <label for="description" class="">Descripción:</label>
                    <textarea name="description" class="form-control form-control-sm description" id="description">{{ $subcurso['descripcion'] }}</textarea>

                    @if ($errors->has('description'))
                        <span class="help-block">
                            <strong>{{ $errors->first('description') }}</strong>
                        </span>
                    @endif
                  </div>
                  <div class="form-group text-center">
                  {!! Form::submit('+ Actualizar subcurso',['class'=>'d-block btn btn-success btn-sm text-center']) !!}
                  </div>
                        </div>
                {!! Form::close() !!}
              </div>
          </div>
    </div>
@endsection
@section('script')
@endsection